name: Build

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build-gcc:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - run: make release CC=gcc
        - run: ./bin/clhasher -ax --b64 --fnv1a 'test_hash'
        - run: make clean

    build-clang:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - run: make release CC=clang
        - run: ./bin/clhasher -ax --b64 --fnv1a 'test_hash'
        - run: make clean
